### ISSUE TITLE
`pyauditor` not installable in Python 3.6

### ISSUE THREAD

**Issue by rfvc** [ALU-Schumacher/AUDITOR#267]
`maturin` used for building `pyauditor` [dropped support](https://github.com/PyO3/maturin/pull/945) for Python3.6 in version 0.13, however in the [pyproject.toml](https://github.com/ALU-Schumacher/AUDITOR/blob/aa231178d12893ffcc0a38ed931e2f83031e4eb7/pyauditor/pyproject.toml#L2) this is given as a requirement to install `pyauditor` with Python 3.6.

**Comment by stefan-k** [comment]
I'm surprised by this because we build 3.6 packages in the CI using maturin. I'll have to investigate. Python 3.6 should be supported though because we deliberately use an older version of PyO3 which still supports 3.6.

**Comment by QuantumDancer** [comment]
Closed due to #371
