### ISSUE TITLE
Typo in description for AUDITOR in the docs

### ISSUE THREAD

**Issue by QuantumDancer** [ALU-Schumacher/AUDITOR#522]
There is a typo/missing word in the introduction for auditor

> and o ers these records to plugins

See:

https://github.com/ALU-Schumacher/AUDITOR/blob/07c10e38a98387a1d8e5bcc3cbf9dccf0078c4aa/media/website/content/_index.md?plain=1#L20-L21

Not sure what this is supposed to mean.

**Comment by stefan-k** [comment]
"offers"

Probably a ligature gone missing when copying from a PDF.

**Comment by QuantumDancer** [comment]
Ah thanks, this makes sense :-)
