### ISSUE TITLE
Use workspace dependencies

### ISSUE THREAD

**Issue by QuantumDancer** [ALU-Schumacher/AUDITOR#788]
As discussed in https://github.com/ALU-Schumacher/AUDITOR/pull/776#discussion_r1577719300 it would be nice to use [workspace dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace) for dependencies that are used in multiple crates.

**Comment by dirksammel** [comment]
Completed by #819
