### ISSUE TITLE
HTCondor Collector stores scroes as integer

### ISSUE THREAD

**Issue by mschnepf** [ALU-Schumacher/AUDITOR#989]
The HTCondor collector uses the `maybe_convert`  function to [convert the score value from the condor query](https://github.com/ALU-Schumacher/AUDITOR/blame/e3c429294ea0ef609cf8e27040ada1670e29a7d1/collectors/htcondor/src/auditor_htcondor_collector/collector.py#L208C58-L208C63). However, [maybe_convert](https://github.com/ALU-Schumacher/AUDITOR/blame/e3c429294ea0ef609cf8e27040ada1670e29a7d1/collectors/htcondor/src/auditor_htcondor_collector/utils.py#L32) tries to convert a string first in integer and when it fails, it tries to convert in float. Therefore, the collector stores numbers as integers.  For that part, a simple convert to `float` should be fine.

**Comment by dirksammel** [comment]
Solved by #990
